baseURL: https://igaing-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Ignacio Gaing
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
         Industrial Engineer, MBA Candidate at @LBS. Passionate about technology and science, with a focus on driving operational and financial performance improvements. Strong analytical skills and a collaborative approach to problem-solving
    
    title: Ignacio Gaing
    subTitle2: Additional information goes here.
  contact:
    address:
      - city: London
        country: UK4
        street: Sussex 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: igaing.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 0754-7633604 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/igaing
      - icon: fa-github
        label: GitHub
        url: https://github.com/IGGAING
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/igaing/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: riskreturn.png
        subtitle: Illuminating My Professional Journey
        title: Curriculum Vitae
        url: blogs/tempus
      - image: riskreturn.png
        subtitle: Embarking on the Investment Odyssey - Navigating Risk for Reward
        title: Risk Return
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Thank you for taking the time to visit my personal webpage. 
    I appreciate your interest and hope you found the content informative and enjoyable.
      \n    If you have any questions, feedback, or inquiries, 
      please don't hesitate to reach out to me.  \n 
      You can contact me using any of the methods listed on the webpage. 
      Whether it's through email, phone, or social media, 
      I'm always available and eager to assist you. \n   
      Once again, thank you for visiting, 
      and I look forward to hearing from you soon."
    title: Thank You
    url: blogs
  markup: 
    goldmark: 
      renderer: 
        unsafe: true